name: CI/CD para index.html

on:
  push:
    branches:
      - main
    path:
      - 'index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          file: CI-CD/Dockerfile
          context: CI-CD/
          push: true
          tags: jerebenitez/cicd-craftech:${{ github.sha }}
